import './globals.css';
import './unistyles';

import type { Metadata } from 'next';
// import localFont from 'next/font/local';
import { Style } from './Style';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const style = `
html, body, #__next {
  -webkit-overflow-scrolling: touch;
}
#__next {
  display: flex;
  flex-direction: column;
  height: 100%;
}
html {
  scroll-behavior: smooth;
  -webkit-text-size-adjust: 100%;
}
body {
  overflow-y: auto;
  overscroll-behavior-y: none;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  -ms-overflow-style: scrollbar;
  font-family: Poppins, "Helvetica Neue", Helvetica, Arial, sans-serif;
}
`;

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" style={{ height: '100%' }}>
            <head>
                <style key="react-native-style" dangerouslySetInnerHTML={{ __html: style }} />

                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={''} />
                <link
                    href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;600;700&display=swap"
                    rel="stylesheet"
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap"
                    rel="stylesheet"
                />
            </head>

            <body className="h-full" style={{ minHeight: '100vh' }}>
                <Style>{children}</Style>
            </body>
        </html>
    );
}
